- fix check mcurses
Changed files:
    xfsdump-miscfix.patch -> 1.5

diff --git a/xfsdump-miscfix.patch b/xfsdump-miscfix.patch
--- a/xfsdump-miscfix.patch
+++ b/xfsdump-miscfix.patch
@@ -1,7 +1,15 @@
-diff -urN xfsdump-1.0.5.org/configure.in xfsdump-1.0.5/configure.in
---- xfsdump-1.0.5.org/configure.in	Tue May  1 22:18:41 2001
-+++ xfsdump-1.0.5/configure.in	Tue May  1 22:56:12 2001
-@@ -173,13 +176,6 @@
+--- xfsdump-2.1.3/configure.in.orig	Thu Aug 15 13:43:40 2002
++++ xfsdump-2.1.3/configure.in	Thu Aug 15 13:45:51 2002
+@@ -156,7 +156,7 @@
+ savedCFLAGS="$CFLAGS"
+ 
+ dnl Checks for curses header and library.
+-AC_CHECK_HEADER(curses.h,, [
++AC_CHECK_HEADER(ncurses/curses.h,, [
+ 	echo
+ 	echo 'FATAL ERROR: could not find a valid curses header.'
+ 	exit 1
+@@ -293,13 +293,6 @@
  dnl also check if man page source is gzipped
  dnl (usually on Debian, but not Redhat pre-7.0)
  have_zipped_manpages=false
